@PersonalFinanceAPI_HostAddress = https://localhost:7005


POST {{PersonalFinanceAPI_HostAddress}}/api/identity/prueba
Content-Type: application/json

{
  "name": "Test Name",
  "email": "test1@test.com",
  "fathersurname": "FatherTest",
  "mothersurname": "MotherTest",
  "rfc": "123456789ABCD",
  "curp": "0123456789ABCDEFGH",
  "nss": "0123456789",
  "dateOfBirth": "1997-07-31",
  "regime": "Regime Test",
  "password": "#Password1"
}

###
